function choice = interface

    d = dialog('Position',[300 300 250 150],'Name','Select One');
    txt = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[20 80 210 40],...
           'String','Select the classifier');
       
    popup = uicontrol('Parent',d,...
           'Style','popup',...
           'Position',[20 70 200 25],...
           'String',{'Filter+classifier';'One Layer Classifier';'Two Layer Classifier'},...
           'Callback',@popup_callback);
       
    btn = uicontrol('Parent',d,...
           'Position',[89 20 70 25],...
           'String','OK',...
           'Callback','delete(gcf)');
       
    choice = 'Filter+classifier';
       
    % Wait for d to close before running to completion
    uiwait(d);
   
       function popup_callback(popup,event)
          idx = popup.Value;
          popup_items = popup.String;
          choice = char(popup_items(idx,:));
       end
end